name = "mord"
author = "jitter"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7fbb8f8cd97fb9c53f336a86b1833e64bd6d33e616fd344efa275d89482f653"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
