name = "mord"
author = "jitter"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0933d1fe1b9f124a5aa978752814eae8df46d213d35fd349b3d54599d2e59bdf"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
