name = "mord"
author = "jitter"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4549335682e90c0393cf2977f3cf7470a7cff0e811073b3bc3fc64f4eeefa4a7"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
