name = "mord"
author = "jitter"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e59416975826135f9dbfc9e9efc7b42ef773cbd00276f9b585a78ae7595749b6"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
